services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: epaycoDb
    volumes:
      - epayco-db-volume:/data/db

volumes:
  epayco-db-volume: