export const INJECTION_TOKENS = {
  // USERS
  USERS_ADAPTER: Symbol('USERS_ADAPTER'),
  USERS_SERVICE: Symbol('USERS_SERVICE'),

  // WALLETS
  WALLETS_ADAPTER: Symbol('WALLETS_ADAPTER'),
  WALLETS_SERVICE: Symbol('WALLETS_SERVICE'),
} as const;
